version: '3'

tasks:
  dependencies:
    desc: Installing the dependencies
    cmds:
      - dotnet restore
  test:
    desc: Running the tests
    cmds:
      - dotnet test --no-build --verbosity normal
  coverage:
    desc: Generating coverage report(s)
    cmds:
      - dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory coverage
  build:
    desc: Building the project
    cmds:
      - dotnet build 
  run-backend:
    desc: Running the backend
    dir: source/WorkSample.Api/bin/Debug/net8.0/
    cmds:
      - Powershell.exe Start-Process -FilePath WorkSample.Api.exe
  run-frontend:
    desc: Running the frontend
    dir: source/WorkSample.Client/bin/Debug/net8.0-windows/
    cmds:
      - Powershell.exe Start-Process -FilePath WorkSample.Client.exe
  run:
    desc: Running everything
    cmds:
      - task: run-backend
      - task: run-frontend
