// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkSample.Persistence.DatabaseContext;

#nullable disable

namespace WorkSample.Persistence.Migrations
{
    [DbContext(typeof(WorkSampleDatabaseContext))]
    [Migration("20240925071041_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkSample.Domain.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2024, 9, 25, 0, 10, 41, 126, DateTimeKind.Local).AddTicks(5320),
                            DateModified = new DateTime(2024, 9, 25, 0, 10, 41, 126, DateTimeKind.Local).AddTicks(5404),
                            Name = "Max",
                            Surname = "Mustermann"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2024, 9, 25, 0, 10, 41, 126, DateTimeKind.Local).AddTicks(5440),
                            DateModified = new DateTime(2024, 9, 25, 0, 10, 41, 126, DateTimeKind.Local).AddTicks(5474),
                            Name = "Erika",
                            Surname = "Musterfrau"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
